name: Build and push Docker image
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: github.repository == 'PluralKit/blueberry'
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          # https://github.com/docker/build-push-action/issues/378
          context: .
          push: true
          tags: |
            ghcr.io/pluralkit/blueberry:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/pluralkit/pluralkit:${{ env.BRANCH_NAME }}
          cache-to: type=inline
